/** Copy for Cash Flow Studio — merged into extendedTranslations per locale. */
export const cashFlowStudioEn = {
  kicker: "Zinvest · Cash Intelligence",
  title: "Cash Flow Studio",
  subtitle:
    "Model income, obligations, and goals; stress-test scenarios; sync insights with ZInvest AI — built like a production finance workstation.",
  resetTemplate: "Reset template",
  analyzeAi: "Analyze with AI",
  thinking: "Thinking…",
  cardMonthlyIncome: "Monthly income",
  cardMonthlyIncomeHint: "Recurring run-rate (yearly ÷12, one-time excluded)",
  cardMonthlyExpenses: "Monthly expenses",
  cardMonthlyExpensesHint: "Fixed + variable + minimum debt payments",
  cardNetCashFlow: "Net cash flow",
  cardNetCashFlowHint: "Income − all budgeted outflows incl. savings & investments",
  cardSavingsRate: "Savings rate",
  cardSavingsRateHint: "Net ÷ income (can be negative if over-allocated)",
  chartTitle: "Income vs expenses",
  chartSubtitle: "12‑month projection · income +{ig}%/yr · expenses +{ee}%/yr",
  chartNetTrajectory: "Net trajectory",
  chartLegendIncome: "Income",
  chartLegendOutflows: "Outflows",
  breakdownTitle: "Expense breakdown",
  breakdownHint: "Operating categories (monthly run‑rate)",
  pctOfIncome: "of income",
  scenarioTitle: "Scenario lab",
  scenarioHint:
    "Stress tests apply instantly to the chart and engine — no separate “calculate” step.",
  scenarioBuyTitle: "What if I buy something?",
  scenarioBuySub: "One-time hit in month 1 of the forecast.",
  scenarioBuyLabelField: "Label",
  scenarioBuyAmountField: "Amount",
  scenarioIncomeDropTitle: "What if income drops?",
  scenarioIncomeDropSub: "Applies to recurring income in projection.",
  scenarioIncomeShockLabel: "Income shock",
  scenarioIncomeGrowth: "Income growth (annual)",
  scenarioExpenseInflation: "Expense inflation (annual)",
  signalsTitle: "Signals & smart suggestions",
  signalsHeuristics: "Heuristic nudges",
  signalsEmpty: "No structural alerts — profile looks balanced.",
  heuristicsEmpty: "Add more category detail to unlock tips.",
  claudeTitle: "ZInvest AI",
  claudeHint: "Structured analysis from your current workbook — risks and a prioritized plan.",
  claudeRiskBadge: "Risk · {level} · {conf}% conf.",
  keyProblems: "Key problems",
  recommendations: "Recommendations",
  claudeEmptyBefore: "Run",
  claudeEmptyBold: "Analyze with AI",
  claudeEmptyAfter: "to synthesize risks and a prioritized action plan from your current workbook + scenario settings.",
  workbook: "Workbook",
  incomeSources: "Income sources",
  fixedExpenses: "Fixed expenses",
  variableExpenses: "Variable expenses",
  debtPayments: "Debt payments",
  savingsAllocations: "Savings allocations",
  investments: "Investments",
  labelName: "Name",
  labelAmount: "Amount",
  labelPayment: "Payment",
  labelPrincipal: "Principal",
  principalPlaceholder: "Optional",
  labelFrequency: "Frequency",
  labelCategory: "Category",
  add: "Add",
  noEntries: "No entries yet — add your first line.",
  removeRow: "Remove row",
  freqMonthly: "Monthly",
  freqYearly: "Yearly",
  freqOneTime: "One-time",
  catHousing: "Housing",
  catFood: "Food",
  catTransport: "Transport",
  catSubscriptions: "Subscriptions",
  catOther: "Other",
  newItem: "New item",
  newDebt: "New debt",
  networkError: "Network error — try again.",
  analyzeFailed: "Analysis failed.",
  aiNotConfigured:
    "ZInvest AI is not configured on this server. Add ANTHROPIC_API_KEY in your host’s environment variables (e.g. Vercel → Project → Settings → Environment Variables), then redeploy.",
  riskLevelLow: "Low",
  riskLevelMedium: "Medium",
  riskLevelHigh: "High",
  ttIncomeLine1: "Recurring income (run-rate): {income}",
  ttIncomeLine2: "Stability index: {stability}/100",
  ttIncomeProjNeg: "Projection: first negative net in month {month}.",
  ttIncomeProjOk: "Projection: net stays non-negative each month (per series).",
  ttExpLine1: "Operating + min. debt: {amount}",
  ttExpLine2: "Expense load vs income: {pct}%",
  ttExpLine3: "All scheduled outflows: {total}/mo",
  ttNetLine1: "Net margin: {margin}%",
  ttNetBurn: "Burn: {burn}/mo",
  ttNetBurnZero: "Burn: $0 (monthly surplus)",
  ttNetRunway: "Cumulative runway ~{month} mo (starting cash 0).",
  ttNetRunwayOk: "Cumulative position stays ≥0 through forecast window.",
  ttNetStability: "Stability: {stability}/100",
  ttSaveLine1: "Net savings rate (after budget): {rate}%",
  ttSaveLine2: "Savings + investments allocation: {alloc}% of income",
  risks: {
    no_income: "No recurring income captured — projections and savings rate are unreliable.",
    negative_runway:
      "Negative monthly cash flow (~{amount}) — spending exceeds inflows after debt, savings, and investments.",
    cumulative_deficit:
      "By month {month}, cumulative cash (starting from zero) falls below zero under current assumptions.",
    negative_projection_month: "Projected net turns negative in month {month}.",
    high_expense_ratio: "Operating expenses consume ~{pct}% of income — limited buffer for shocks.",
    single_income:
      "Income is concentrated in a single source — consider diversification or an emergency reserve.",
    dominant_income:
      "One income stream dominates (>92%) — a disruption would materially impact cash flow.",
    subscription_load: "Subscriptions are a noticeable slice of income — good candidate for consolidation.",
    housing_stress: "Housing costs exceed ~35% of income — classic affordability stress signal.",
    low_savings_rate: "Net savings rate is under 10% of income — limited cushion for shocks.",
  },
  cardHints: {
    single_income_stream: "Single recurring income stream — diversification reduces shock risk.",
    housing_pressure: "Housing >35% of income — affordability pressure.",
    high_load: "High operating load vs income — thin margin.",
    net_cumulative_risk: "Cumulative cash risk by month {month}.",
    net_negative: "Monthly net is negative — burn exceeds inflows.",
    net_projection_dip: "Net dips negative in month {month} in the projection.",
    savings_overallocated: "Over-allocated vs income — net rate below zero.",
    savings_low: "Net savings rate under 10% — limited cushion.",
  },
  suggestionTitles: {
    food_trim: "Food spend is elevated",
    sub_audit: "Subscription stack",
    thin_surplus: "Thin surplus",
    misc_bucket: "Large “other” bucket",
  },
  suggestions: {
    food_trim:
      "About {pct}% of income goes to food. Many households aim for ~15–20% by mixing meal prep with dining out.",
    sub_audit:
      "You have {count} subscription line(s) (~{pct}% of income). Audit overlapping tools and annual billing discounts.",
    thin_surplus:
      "Net cash flow is positive but narrow — small income dips or expense spikes could flip you negative.",
    misc_bucket:
      "Miscellaneous variable spend is high — split into specific categories to find leaks.",
  },
} as const;

export const cashFlowStudioRu = {
  kicker: "Zinvest · Аналитика денег",
  title: "Студия денежного потока",
  subtitle:
    "Моделируйте доходы, обязательства и цели; стресс‑тесты сценариев; инсайты через ZInvest AI — как в рабочей станции финансового аналитика.",
  resetTemplate: "Сбросить шаблон",
  analyzeAi: "Анализ с ИИ",
  thinking: "Думаю…",
  cardMonthlyIncome: "Месячный доход",
  cardMonthlyIncomeHint: "Повторяющийся доход (год ÷12, разовые не в базе)",
  cardMonthlyExpenses: "Месячные расходы",
  cardMonthlyExpensesHint: "Фикс + переменные + мин. платежи по долгам",
  cardNetCashFlow: "Чистый денежный поток",
  cardNetCashFlowHint: "Доход − все запланированные расходы, долги, сбережения и инвестиции",
  cardSavingsRate: "Норма сбережений",
  cardSavingsRateHint: "Чистый поток ÷ доход (может быть отрицательной при перерасходе)",
  chartTitle: "Доходы и расходы",
  chartSubtitle: "Прогноз на 12 мес. · доход +{ig}%/год · расходы +{ee}%/год",
  chartNetTrajectory: "Динамика чистого потока",
  chartLegendIncome: "Доход",
  chartLegendOutflows: "Расходы",
  breakdownTitle: "Структура расходов",
  breakdownHint: "Категории операционных расходов (месячная база)",
  pctOfIncome: "от дохода",
  scenarioTitle: "Лаборатория сценариев",
  scenarioHint: "Стресс‑тесты сразу пересчитывают график и модель — без отдельной кнопки «Посчитать».",
  scenarioBuyTitle: "Что если куплю?",
  scenarioBuySub: "Разовая выплата в 1‑м месяце прогноза.",
  scenarioBuyLabelField: "Название",
  scenarioBuyAmountField: "Сумма",
  scenarioIncomeDropTitle: "Что если доход упадёт?",
  scenarioIncomeDropSub: "Применяется к повторяющемуся доходу в прогнозе.",
  scenarioIncomeShockLabel: "Шок по доходу",
  scenarioIncomeGrowth: "Рост дохода (год)",
  scenarioExpenseInflation: "Инфляция расходов (год)",
  signalsTitle: "Сигналы и подсказки",
  signalsHeuristics: "Эвристики",
  signalsEmpty: "Структурных предупреждений нет — профиль выглядит сбалансированным.",
  heuristicsEmpty: "Добавьте детализацию по категориям — откроются советы.",
  claudeTitle: "ZInvest AI",
  claudeHint: "Структурированный разбор по вашей книге — риски и приоритетный план действий.",
  claudeRiskBadge: "Риск · {level} · увер. {conf}%",
  keyProblems: "Главные проблемы",
  recommendations: "Рекомендации",
  claudeEmptyBefore: "Нажмите",
  claudeEmptyBold: "Анализ с ИИ",
  claudeEmptyAfter: "— чтобы получить риски и план действий по книге и сценариям.",
  workbook: "Книга данных",
  incomeSources: "Источники дохода",
  fixedExpenses: "Фиксированные расходы",
  variableExpenses: "Переменные расходы",
  debtPayments: "Платежи по долгам",
  savingsAllocations: "Сбережения (план)",
  investments: "Инвестиции",
  labelName: "Название",
  labelAmount: "Сумма",
  labelPayment: "Платёж",
  labelPrincipal: "Основной долг",
  principalPlaceholder: "Необязательно",
  labelFrequency: "Период",
  labelCategory: "Категория",
  add: "Добавить",
  noEntries: "Пока нет строк — добавьте первую.",
  removeRow: "Удалить строку",
  freqMonthly: "Ежемесячно",
  freqYearly: "Ежегодно",
  freqOneTime: "Разово",
  catHousing: "Жильё",
  catFood: "Еда",
  catTransport: "Транспорт",
  catSubscriptions: "Подписки",
  catOther: "Другое",
  newItem: "Новая строка",
  newDebt: "Новый долг",
  networkError: "Ошибка сети — попробуйте снова.",
  analyzeFailed: "Анализ не выполнен.",
  aiNotConfigured:
    "ZInvest AI на сервере не настроен. Добавьте переменную ANTHROPIC_API_KEY в настройках хостинга (например Vercel → Project → Settings → Environment Variables) и выполните redeploy.",
  riskLevelLow: "Низкий",
  riskLevelMedium: "Средний",
  riskLevelHigh: "Высокий",
  ttIncomeLine1: "Повторяющийся доход (база): {income}",
  ttIncomeLine2: "Индекс устойчивости: {stability}/100",
  ttIncomeProjNeg: "Прогноз: первый минус по нетто в месяце {month}.",
  ttIncomeProjOk: "Прогноз: нетто не уходит в минус по месяцам (по ряду).",
  ttExpLine1: "Оперрасходы + мин. долги: {amount}",
  ttExpLine2: "Нагрузка на доход: {pct}%",
  ttExpLine3: "Все исходящие платежи: {total}/мес",
  ttNetLine1: "Маржа нетто: {margin}%",
  ttNetBurn: "Выгорание: {burn}/мес",
  ttNetBurnZero: "Выгорание: 0 (профицит)",
  ttNetRunway: "Накопленный риск ~{month} мес (старт с нуля).",
  ttNetRunwayOk: "Накопленная позиция ≥0 в окне прогноза.",
  ttNetStability: "Устойчивость: {stability}/100",
  ttSaveLine1: "Норма сбережений (после бюджета): {rate}%",
  ttSaveLine2: "Доля сбережений + инвестиций: {alloc}% от дохода",
  risks: {
    no_income: "Нет учтённого повторяющегося дохода — прогноз и норма сбережений ненадёжны.",
    negative_runway:
      "Отрицательный месячный поток (~{amount}) — расходы превышают приток с учётом долгов, сбережений и инвестиций.",
    cumulative_deficit:
      "К месяцу {month} накопленная позиция (от нуля) уходит в минус при текущих допущениях.",
    negative_projection_month: "В месяце {month} прогнозное нетто становится отрицательным.",
    high_expense_ratio: "Оперрасходы ~{pct}% дохода — мало буфера на шоки.",
    single_income: "Доход из одного источника — подумайте о диверсификации и резерве.",
    dominant_income: "Один поток >92% дохода — сбой ударит по потоку наличности.",
    subscription_load: "Заметная доля подписок — стоит консолидировать.",
    housing_stress: "Жильё >35% дохода — классический сигнал нагрузки.",
    low_savings_rate: "Чистая норма сбережений <10% — мало подушки.",
  },
  cardHints: {
    single_income_stream: "Один повторяющийся доход — выше риск шока.",
    housing_pressure: "Жильё >35% дохода — давление на бюджет.",
    high_load: "Высокая нагрузка расходов — тонкая маржа.",
    net_cumulative_risk: "Риск по накоплению к месяцу {month}.",
    net_negative: "Месячное нетто отрицательное — расход больше притока.",
    net_projection_dip: "В месяце {month} нетто уходит в минус в прогнозе.",
    savings_overallocated: "Перерасход относительно дохода — норма ниже нуля.",
    savings_low: "Норма сбережений <10% — мало запаса.",
  },
  suggestionTitles: {
    food_trim: "Высокие расходы на еду",
    sub_audit: "Стопка подписок",
    thin_surplus: "Тонкий профицит",
    misc_bucket: "Большая категория «прочее»",
  },
  suggestions: {
    food_trim:
      "Около {pct}% дохода на еду. Часто целятся в 15–20% за счёт готовки и реже выходов.",
    sub_audit:
      "{count} строк подписок (~{pct}% дохода). Проверьте дубли и годовую оплату.",
    thin_surplus:
      "Профицит есть, но узкий — небольшой спад дохода или скачок расхода перевернёт баланс.",
    misc_bucket: "Много «прочих» переменных — разбейте на категории, чтобы найти утечки.",
  },
} as const;

export const cashFlowStudioUz = {
  kicker: "Zinvest · Naqd tahlil",
  title: "Naqd oqimi studiyasi",
  subtitle:
    "Daromad, majburiyat va maqsadlarni modellashtiring; stress-sinariylar; ZInvest AI bilan tahlil — professional moliya ish maydoni.",
  resetTemplate: "Shabloni tiklash",
  analyzeAi: "AI tahlili",
  thinking: "O‘ylayapman…",
  cardMonthlyIncome: "Oylik daromad",
  cardMonthlyIncomeHint: "Takroriy bazavar (yil ÷12, bir martalik chiqariladi)",
  cardMonthlyExpenses: "Oylik xarajatlar",
  cardMonthlyExpensesHint: "Doimiy + o'zgaruvchan + qarzning min. to'lovlari",
  cardNetCashFlow: "Sof naqd oqimi",
  cardNetCashFlowHint: "Daromad − barcha rejali chiqimlar, qarz, jamg'arma va investitsiyalar",
  cardSavingsRate: "Jamg'arma stavkasi",
  cardSavingsRateHint: "Sof oqim ÷ daromad (ortiqcha rejada manfiy bo'lishi mumkin)",
  chartTitle: "Daromad va xarajatlar",
  chartSubtitle: "12 oy prognoz · daromad +{ig}%/yil · xarajat +{ee}%/yil",
  chartNetTrajectory: "Sof oqim dinamikasi",
  chartLegendIncome: "Daromad",
  chartLegendOutflows: "Chiqimlar",
  breakdownTitle: "Xarajat tuzilishi",
  breakdownHint: "Operatsion toifalar (oylik bazaviy)",
  pctOfIncome: "darajdan",
  scenarioTitle: "Ssenariy laboratoriyasi",
  scenarioHint:
    "Stress-sinariylar grafik va modelni darhol qayta hisoblaydi — alohida «hisoblash» tugmasi yo‘q.",
  scenarioBuyTitle: "Agar nimadir sotib olsam?",
  scenarioBuySub: "Prognozning 1-oyida bir martalik chiqim.",
  scenarioBuyLabelField: "Nomi",
  scenarioBuyAmountField: "Summa",
  scenarioIncomeDropTitle: "Daromad tushsa?",
  scenarioIncomeDropSub: "Prognozda takroriy daromadga qo‘llanadi.",
  scenarioIncomeShockLabel: "Daromad shoki",
  scenarioIncomeGrowth: "Daromad o‘sishi (yillik)",
  scenarioExpenseInflation: "Xarajat inflyatsiyasi (yillik)",
  signalsTitle: "Signallar va maslahatlar",
  signalsHeuristics: "Evristikalar",
  signalsEmpty: "Strukturaviy ogohlantirish yo‘q — profil muvozanatli.",
  heuristicsEmpty: "Toifalarni batafsil qo‘shing — maslahatlar ochiladi.",
  claudeTitle: "ZInvest AI",
  claudeHint: "Joriy ish kitobi bo‘yicha tuzilgan tahlil — xavflar va ustuvor reja.",
  claudeRiskBadge: "Xavf · {level} · ishonch {conf}%",
  keyProblems: "Asosiy muammolar",
  recommendations: "Tavsiyalar",
  claudeEmptyBefore: "",
  claudeEmptyBold: "AI tahlili",
  claudeEmptyAfter: "ni bosing — xavflar va harakat rejasi chiqadi.",
  workbook: "Ma'lumotlar kitobi",
  incomeSources: "Daromad manbalari",
  fixedExpenses: "Doimiy xarajatlar",
  variableExpenses: "O'zgaruvchan xarajatlar",
  debtPayments: "Qarz to'lovlari",
  savingsAllocations: "Jamg'arma (reja)",
  investments: "Investitsiyalar",
  labelName: "Nomi",
  labelAmount: "Summa",
  labelPayment: "To'lov",
  labelPrincipal: "Asosiy qarz",
  principalPlaceholder: "Ixtiyoriy",
  labelFrequency: "Davriylik",
  labelCategory: "Toifa",
  add: "Qo‘shish",
  noEntries: "Hali qator yo‘q — birinchisini qo‘shing.",
  removeRow: "Qatorni olib tashlash",
  freqMonthly: "Oylik",
  freqYearly: "Yillik",
  freqOneTime: "Bir martalik",
  catHousing: "Uy-joy",
  catFood: "Oziq-ovqat",
  catTransport: "Transport",
  catSubscriptions: "Obunalar",
  catOther: "Boshqa",
  newItem: "Yangi qator",
  newDebt: "Yangi qarz",
  networkError: "Tarmoq xatosi — qayta urinib ko‘ring.",
  analyzeFailed: "Tahlil bajarilmadi.",
  aiNotConfigured:
    "ZInvest AI serverda sozlanmagan. ANTHROPIC_API_KEY ni hosting muhit o‘zgaruvchilariga qo‘shing (masalan Vercel → Project → Settings → Environment Variables) va qayta deploy qiling.",
  riskLevelLow: "Past",
  riskLevelMedium: "O'rtacha",
  riskLevelHigh: "Yuqori",
  ttIncomeLine1: "Takroriy daromad (baza): {income}",
  ttIncomeLine2: "Barqarorlik indeksi: {stability}/100",
  ttIncomeProjNeg: "Prognoz: {month}-oyda sof netto birinchi marta manfiy.",
  ttIncomeProjOk: "Prognoz: oy bo‘yicha sof netto manfiy bo‘lmaydi.",
  ttExpLine1: "Operatsion + min. qarz: {amount}",
  ttExpLine2: "Daromadga yuk: {pct}%",
  ttExpLine3: "Barcha rejali chiqimlar: {total}/oy",
  ttNetLine1: "Sof marja: {margin}%",
  ttNetBurn: "Yonish: {burn}/oy",
  ttNetBurnZero: "Yonish: 0 (profisit)",
  ttNetRunway: "Yig‘ma xavf ~{month} oy (noldan boshlab).",
  ttNetRunwayOk: "Prognoz oynasida yig‘ma pozitsiya ≥0.",
  ttNetStability: "Barqarorlik: {stability}/100",
  ttSaveLine1: "Jamg‘arma stavkasi (byudjetdan keyin): {rate}%",
  ttSaveLine2: "Jamg‘arma + investitsiya ulushi: {alloc}% darajdan",
  risks: {
    no_income: "Takroriy daromad ko‘rsatilmagan — prognoz va stavka ishonchsiz.",
    negative_runway:
      "Manfiy oylik oqim (~{amount}) — chiqimlar qarz, jamg‘arma va investitsiyalardan keyin ham oshib ketadi.",
    cumulative_deficit:
      "{month}-oyda jamlangan pozitsiya (noldan) manfiy bo‘ladi (joriy taxminlar bilan).",
    negative_projection_month: "{month}-oyda prognoz sof netto manfiy bo‘ladi.",
    high_expense_ratio: "Operatsion xarajatlar ~{pct}% daraj — shokkarga kam zaxira.",
    single_income: "Bir manbadan daromad — diversifikatsiya va zaxira o‘ylang.",
    dominant_income: "Bir oqim >92% daraj — uzilsa katta ta’sir.",
    subscription_load: "Obunalar sezilarli ulush — birlashtirish foydali.",
    housing_stress: "Uy-joy >35% daraj — klassik yuk.",
    low_savings_rate: "Sof jamg‘arma stavkasi <10% — kam zaxira.",
  },
  cardHints: {
    single_income_stream: "Bitta takroriy manba — shok xavfi yuqori.",
    housing_pressure: "Uy-joy >35% daraj — byudjet bosimi.",
    high_load: "Yuqori xarajat yuki — ingichka marja.",
    net_cumulative_risk: "{month}-oygacha yig‘ma xavf.",
    net_negative: "Oylik sof manfiy — chiqim oshib ketdi.",
    net_projection_dip: "Prognozda {month}-oyda sof minusa tushadi.",
    savings_overallocated: "Darajdan ortiq rejalar — stavka manfiy.",
    savings_low: "Jamg‘arma stavkasi <10% — kam yostiqcha.",
  },
  suggestionTitles: {
    food_trim: "Oziq-ovqat xarajati baland",
    sub_audit: "Obunalar to‘plami",
    thin_surplus: "Ingichka profisit",
    misc_bucket: "Katta «boshqa» toifasi",
  },
  suggestions: {
    food_trim:
      "Darajning ~{pct}% oziq-ovqatga. Ko‘pchilik 15–20% ga pishirish va kamroq chiqish bilan intiladi.",
    sub_audit:
      "{count} obuna qatori (~{pct}% daraj). Dublikatlarni va yillik to‘lovni tekshiring.",
    thin_surplus:
      "Profisit bor, lekin tor — kichik tushish yoki xarajat sakrashi hammasini ag‘daradi.",
    misc_bucket: "Ko‘p «boshqa» — toifalarga bo‘ling, sizib chiqishni toping.",
  },
} as const;
